version: '3.8'

services:
    php:
        image: ghcr.io/sylius/docker-images-php:8.0-fpm-0.6.0
        working_dir: /app
        user: www-data
        environment:
            APP_DEBUG: 1
        depends_on:
            - mysql
        volumes:
            - .:/app:delegated
            - ./docker/php/php.ini-development:/usr/local/etc/php/php.ini:delegated

    nginx:
        image: nginx:stable-alpine
        working_dir: /app
        depends_on:
            - php
        volumes:
            - .:/app:delegated
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
        ports:
            - "8080:80"

    mysql:
        image: mysql:latest
        command:
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"
            - "--enforce-gtid-consistency=ON"
            - "--gtid-mode=ON"
            - "--binlog-format=ROW"
            - "--sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
            - "--default_authentication_plugin=mysql_native_password"
        environment:
            MYSQL_ROOT_PASSWORD: 'sylius'
