version: '3.9'

volumes:
    public:

services:
    php:
        build:
            context: .
        working_dir: /app
        volumes:
            - public:/app/public
        depends_on:
            - mysql

    nginx:
        image: nginx:stable-alpine
        working_dir: /app
        volumes:
            - public:/app/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        ports:
            - "8080:80"

    mysql:
        image: mysql:latest
        command:
            - "mysqld"
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"
            - "--enforce-gtid-consistency=ON"
            - "--gtid-mode=ON"
            - "--binlog-format=ROW"
            - "--sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,ANSI_QUOTES"
            - "--default_authentication_plugin=mysql_native_password"
        volumes:
            - ./docker/mysql/fixtures.sql:/fixtures.sql
        environment:
            MYSQL_ROOT_PASSWORD: 'sylius'
